sortlist=[
    ['採掘した回数',"minecraft:mined"],
    ['使用した回数',"minecraft:used"],
    ['クラフトした回数',"minecraft:crafted"],
    ['拾った回数',"minecraft:picked_up"],
    ['捨てた回数',"minecraft:dropped"],
    ['殺した数',"minecraft:killed"],
    ['殺された数',"minecraft:killed_by"],
    ['統計',"minecraft:custom"]
]